### ISSUE TITLE
Feature request: forbid to play sound while another sound is playing

### ISSUE THREAD

**Issue by AdamSedlacek** [AdamSedlacek/PB138-ZooA#2]
In "_some-animal_.js", there are two buttons - "play sound" and "read text" button.
There is currently no feature, that would forbid to play both sounds simultaneously.

**Comment by katyzubnar** [comment]
Solved with commit https://github.com/AdamSedlacek/PB138-ZooA/commit/2d9d3ee3f5456d265b6ca0a30f4cca6acd1eac9f
